### ISSUE TITLE
Passing dynamic params

### ISSUE THREAD

**Issue by romafederico** [Developero-official/mysql-mongo-db#1]
Hi there!

Thanks for building this and make it public. I have a quick question... I am trying to do

> mongo.find(StoryModel, null, (err, docs) => {
    if (err) throw err;
    docs.forEach(story => {
        let columns = [ 'IdCapitulo', 'IdContenido', 'Titulo', 'Contenido' ];
        let params = { where: 'IdContenido = story.story_id' };
        mysql.select('NMW_Contenidos_Capitulos', columns, params, (err, res, fields) => {
            if(err) throw err;
            console.log(res);
        })
    })
});

 
How can I pass the story.story_id value to params?

**Comment by romafederico** [comment]
Olvidate de mi pregunta. Lo resolvi con 

let params = { where: 'IdContenido = ' + story.story_id };

**Comment by juan-carlos-correa** [comment]
Excelente, me da gusto que pudieras resolverlo
